### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/Mod-Twilight-Forest#2]
update readme

to add your name and my name

**Comment by tobyplowy** [comment]
@lipki can you plese update the readme

**Comment by lipki** [comment]
it will be updated when I make the release.
Meanwhile you can do it yourself.
https://github.com/SummerFields/Mod-Twilight-Forest/edit/master/README.md
if you want.

**Comment by lipki** [comment]
no no no, go, a little effort will change the readme :D

**Comment by tobyplowy** [comment]
But I alredi Changed It
